language: objective-c
osx_image: xcode7.3
before_install:
  - brew update
  - brew upgrade python
  - nvm install v8.7.0
  - brew install opam
  - opam init -y
  - opam switch "$OCAML_VERSION"
  - eval `opam config env`
  - opam update
before_script:
  - opam pin add -y rethereum .
script:
  - npm run test
  - git diff --exit-code
env:
  - OCAML_VERSION=4.02.3
  - OCAML_VERSION=4.03.0
  - OCAML_VERSION=4.04.0
  - OCAML_VERSION=4.06.0
notifications:
  email:
    - careyjanecka@gmail.com
